name: Suggestion
description: Suggest a new feature or the possible implementation of an already suggested feature
labels: ["suggestion"]
projects: ["kegomimu/1"]
body:
  - type: textarea
    id: content
    attributes:
      label: Description
      placeholder: Include as much details as possible
    validations:
      required: true
  - type: dropdown
    id: suggestion-type
    attributes:
      label: Type
      description: Affected parts of the project
      options:
        - Structures
        - Encryption
        - Security
        - Other
      default: 0
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Terms
      options:
        - label: This issue does not exist yet
          required: true
