name: Suggestion
description: Suggest a new feature or the possible implementation of an already suggested feature
title: "Suggestion"
labels: ["suggestion"]
projects: ["kegomimu/1"]
assignees:
  - kegomimu
body:
  - type: textarea
    id: content
    attributes:
      label: Description
      description: Include as much details as possible
      placeholder: One step ahead
      value: "Tell us more about your suggestion"
    validations:
      required: true
  - type: dropdown
    id: suggestion-type
    attributes:
      label: Affected code part
      description: Which code part is the suggestion for?
      options:
        - Structures
        - Encryption
        - Security
        - Other
      default: 0
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Terms
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
        - label: This issue does not exist yet
